name: flutter_resto
description: A modern restaurant listing application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  android_alarm_manager_plus: ^4.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.4.0
  flutter_local_notifications: ^19.2.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.5
  workmanager: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
